### PR TITLE
Fix #207 - Resolve issues with Login7 Payload

### LINKED ISSUE #207: NTLM Login problem
Hi,

Are there any tricks to getting the NTLM authentication to work (such as FQDN, formats, TDS versions, etc)?  No matter what I try I get:

    Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

My config looks like this:

    {
      userName: 'my_domain_user'",
      password: 'my_domain_password",
      domain: 'my.fq.dn',
      server: '192.168.xx.xx',
      options: { database: 'my_db' }
    }

I've also tried using non-FQDN for the domain.  No difference.  It works if I remove `domain` and changed to SQL Server user.

Any ideas?  Thanks!

### PR DESCRIPTION
**Pull request by arobson**
This should resolve both #207 and #214. After this fix, I was able to connect to a SQL Server on an AD machine using AD credentials from both OS X and Ubuntu machines that were not members of the AD domain. Planning on further integration testing, but wanted to  get the conversation started. (cc @bretcope, @rossipedia)

### CODE REVIEW

File: src/login7-payload.coffee [hunk 1]
```diff
@@ -249,6 +249,7 @@ class Login7Payload
 
   createNTLMRequest: (options) ->
     domain = escape(options.domain.toUpperCase())
+    workstation = escape( if options.workstation then options.workstation.toUpperCase() else '')
```
Comment (arthurschreiber) [inline src/login7-payload.coffee]: better:

```coffee
workstation = if options.workstation then escape(options.workstation.toUpperCase()) else ''
```

Comment (arobson) [inline src/login7-payload.coffee]: Good catch, thanks :+1:

**Comment by bretcope** [comment]
Awesome. I'd like a few more people to try this out and see it it works for them, and I'd love testing like you mentioned, but it would be great to get this merged asap.

**Comment by arobson** [comment]
@bretcope - thanks to the awesome ops team at work, I discovered that my changes still didn't correctly handle scenarios where NTLMv2 Session Security is a requirement. My [last commit](https://github.com/arobson/tedious/commit/e0020b7b3cc2c3dbf5172ffd2d789f1d819be4ab) resolves this in our test environment and we will verify in production tomorrow.

**Comment by ifandelse** [comment]
Definitely interested in hearing how this is going for other people. It's working well for us at LeanKit thus far. If you need anything from us before you can merge, let us know!

**Comment by arobson** [comment]
@bretcope - Is there anything I can do to help get this PR merged in? We're using my fork right now at work and have to have forks of several other upstream projects as a result. I'd really hate to see this PR go unmerged since (at the very least) it solved our issues with AD based NTLM. I have a small dev environment setup (AD Controller + SQL Server) and would be happy to demo it. I'd also be glad to provide instructions for how to test it if that would help.

**Comment by bretcope** [comment]
I'll let @arthurschreiber handle this PR. I don't have any objections.

**Comment by arobson** [comment]
@arthurschreiber - is there anything I can do that would help resolve this PR? Thanks!

**Comment by arthurschreiber** [comment]
Hey there! I'm on a trip right now, so I can't get this merged right now. But I'll look into merging and releasing this once I'm back at he next week.=

**Comment by arthurschreiber** [comment]
@arobson I'll merge this for now. Is there some way this could be integration tested with the Appveyor CI environment we have?

**Comment by arobson** [comment]
@arthurschreiber - thanks! Unless there is a way to setup an environment in Appveyor with a DC controller AND a separate SQL machine that's joined to the AD, I don't know how you would manage this as part of your build. Unfortunately, SQL cannot be installed on a Domain Controller and still function correctly, so it takes 2 machines/VM instances to reproduce the issue.

**Comment by arthurschreiber** [comment]
Gah, that sounds super inconvenient. Oh well. :cry:

**Comment by Draffodx** [comment]
Hi,

Is this fix included if I use npm install tedious today?

I am trying to use Tedious to connect to a MS SQL Server DB from my local machine but the authentication is failing so I'm not sure if this fix is included in the release?

If it is included is there any example code available for how to access a MS SQL Server DB using Windows Authentication?

**Comment by bretcope** [comment]
The most recent version `1.11.0` has everything that's in master.

**Comment by Draffodx** [comment]
@bretcope - Thanks, I have made sure it is version 1.11.0 yet I cannot connect to the MS SQL Server instance using Tedious. My code is as follows:

```javascript
var Connection = require('tedious').Connection;

//Set up config for logging into the DB
var config = {
    userName: '$username001', //Username
    domainName: "DOMAIN", //Domain
    password: 'pass.word', //Password
    server: 'XX.XX.XX.XX', //Database address
    options: {
        readOnlyIntent: true
    }
};

var connection = new Connection(config);

    //When the database is connected to we get this event
    connection.on('connect', function(err) {
            // If no error, then good to go...
            if(err){
                console.log('err = ' + err); //Log the error to the console
            }
            else{
                console.log('success'); //Log the success to the console
            }
        }
    );
    connection.on('errorMessage',  function(err){
        console.log('full error = ' + JSON.stringify(err)); //Log the error to the console
    });
```

But this fails with the following logs:

> debug = connected to XX.XX.XX.XX.XXXX
> debug = State change: Connecting -> SentPrelogin
> debug = State change: SentPrelogin -> SentLogin7WithStandardLogin
> full error = {"number":18456,"state":1,"class":14,"message":"Login failed for user  '$username001'.","serverName":"subdomain","procName":"","lineNumber":1,"name":"ERROR","event":"errorMessage"}
> err = ConnectionError: Login failed for user '$username001'.
> debug = State change: SentLogin7WithStandardLogin -> Final
> debug = connection to XX.XX.XX.XX.XXXX closed
> debug = State is already Final

So I am wondering if its actually possible to connect like this to a MS SQL Server? Has this been confirmed to work and if so is there documentation on a config that works with Windows Authentication/NTLM on Tedious?

**Comment by arobson** [comment]
Hi, @Draffodx - we currently use this feature in production at LeanKit without issues on SQL Server 2012. Have you been able to successfully connect to your server with those credentials using SSMS or another library?

**Comment by Draffodx** [comment]
Hi @arobson I have not been able to get a connection to the SQL Server using Tedious, to test the connection I wrote a Python script using Pymssql and I was able to connect to the SQL server using Python but so far I have not been successful with trying to connect using NodeJS.

**Comment by lloydcotten** [comment]
@Draffodx In your config, you have `domainName`.  I think the config option property name should be `domain`:
```javascript
//Set up config for logging into the DB
var config = {
    userName: '$username001', //Username
    domain: "DOMAIN", //Domain
    password: 'pass.word', //Password
    server: 'XX.XX.XX.XX', //Database address
    options: {
        readOnlyIntent: true
    }
};
```

**Comment by Draffodx** [comment]
@lloydcotten - Something like this?

'''javascript
//Set up config for logging into the DB
var config = {
    userName: '$username001', //Username
    password: 'pass.word', //Password
    server: 'XX.XX.XX.XX', //Database address
    options: {
        readOnlyIntent: true,
        name: "DOMAIN"
    }
}; '''

Even with that it still fails with the same error.

**Comment by arthurschreiber** [comment]
`domain:`, not `name:`

**Comment by lloydcotten** [comment]
And not in the `options` object - up along side `userName` and `password`.  Exactly like my example.  I  edited my first response, since I see how my wording perhaps was confusing.

**Comment by Draffodx** [comment]
That seems to have been my mistake, it is connecting now, thanks very much for the help, it is much appreciated.

**Comment by jgornick** [comment]
I noticed the addition of "workstation" added to connection options. Does that need to be specified in order to authenticate from a non-trusted *nix instance?
